### ISSUE TITLE
ghosting rois

### ISSUE THREAD

**Issue by cjstarling** [YassineRMH/MATLAB_ACR_Automation#3]
occasionally a ghosting roi will be placed too close to the edge of the image, such that part of its area is outside the image, I may have seen this with other tests using bkg rois.

Would it be possible to limit the roi placement so it can't do this, such as rejecting any placement that doesn't have an equal area to the other rois?

**Comment by YassineRMH** [comment]
This shouldn't be too difficult to fix. I'll prioritize this.
